ignores_function_declarations: true
ignores_comments: true

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - number_separator
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - last_where
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - private_action
  - private_outlet
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_declaration
  - unused_import
  - force_try

identifier_name:
  excluded:
    - id
    - x
    - y

colon:
  flexible_right_spacing: true
